name: CI/CD Pipeline

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        if [ -f backend/requirements.txt ]; then pip install -r backend/requirements.txt; fi
    
    - name: Load .env file
      id: env
      run: |
        echo "Loading .env file"
        if [ -f .env ]; then
          # Export all variables from .env file
          export $(grep -v '^#' .env | xargs)
          # Make DATABASE_URL available to subsequent steps
          echo "DATABASE_URL=$DATABASE_URL" >> $GITHUB_ENV
          echo "Loaded DATABASE_URL from .env"
        else
          echo ".env file not found"
          exit 1
        fi
    
    - name: Run tests
      env:
        DATABASE_URL: ${{ env.DATABASE_URL }}
      run: |
        cd backend
        python -m pytest -v

  deploy:
    needs: test
    if: github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        if [ -f backend/requirements.txt ]; then pip install -r backend/requirements.txt; fi
    
    - name: Deploy to Production
      run: |
        echo "Deployment would happen here"
        # Add your deployment commands here
        # For example:
        # - Install deployment tools
        # - Configure deployment environment
        # - Run deployment scripts
